# Filesystem Output
project: runs/segment
name: yolo-seg-baseline-no-aug
exist_ok: false

# Logging
wandb: true
wandb_entity: dlbs-jf
wandb_project: runs-segment

# Core
model: yolo11s-seg.pt
data: /mnt/nas05/data01/slg-q1/dlbs/yolo_dataset/data.yaml
epochs: 2000
imgsz: 640
batch: 16
device: cuda       
patience: 100
seed: 42
deterministic: true


# force a fixed learning rate 
warmup_epochs: 0
warmup_momentum: 0.0
warmup_bias_lr: 0.0
lr0: 0.0015
lrf: 1.0


# Output artefacts
save: true
plots: true

# Turn off augmentation 
degrees: 0.0
translate: 0.0
scale: 0.0
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.0

hsv_h: 0.0
hsv_s: 0.0
hsv_v: 0.0

mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
erasing: 0.0
auto_augment: null
close_mosaic: 0
